# Generated by Django 6.0.2 on 2026-02-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emeuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
