# Generated by Django 5.1.2 on 2026-02-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_emeuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='emeuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
