# Generated by Django 5.1.2 on 2026-03-06 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_wallpost_wallcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallcomment",
            name="sync_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="wallpost",
            name="sync_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
