# Generated by Django 5.1.2 on 2026-03-03 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("emoji", models.CharField(default="📋", max_length=10)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("life", "❤️ Особисте"),
                            ("business", "💼 Бізнес"),
                            ("eme", "⚡ EME"),
                            ("tech", "🔧 Технічне"),
                            ("community", "🤝 Спільнота"),
                        ],
                        default="eme",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("this_week", "Цього тижня"),
                            ("in_progress", "В роботі"),
                            ("done", "Готово"),
                            ("frozen", "Заморожено"),
                        ],
                        default="backlog",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "🔴 Критичний"),
                            ("high", "🟡 Високий"),
                            ("medium", "🟢 Середній"),
                            ("low", "⚪ Низький"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("next_action", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-priority", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("is_done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["is_done", "created_at"],
            },
        ),
    ]
