# Generated by Django 5.1.2 on 2026-03-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_options_projectaction_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectaction",
            name="assignee_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_actions",
                to="projects.projectrole",
            ),
        ),
    ]
