# Generated by Django 5.1.2 on 2026-03-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_action_assignee_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="domain",
            field=models.CharField(
                choices=[
                    ("life", "❤️ Особисте"),
                    ("business", "💼 Бізнес"),
                    ("eme", "⚡ EME"),
                    ("tech", "🔧 Технічне"),
                    ("community", "🤝 Спільнота"),
                    ("games", "🎮 Ігри"),
                ],
                default="eme",
                max_length=20,
            ),
        ),
    ]
