# Generated by Django 5.1.2 on 2026-03-06 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sync_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="projectaction",
            name="sync_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="sync_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="projectrole",
            name="sync_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="domain",
            field=models.CharField(
                choices=[
                    ("life", "❤️ Особисте"),
                    ("business", "💼 Бізнес"),
                    ("eme", "⚡ EME"),
                    ("tech", "🔧 Технічне"),
                    ("community", "🤝 Спільнота"),
                ],
                default="eme",
                max_length=20,
            ),
        ),
    ]
