# Generated by Django 5.1.2 on 2026-03-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KBCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("emoji", models.CharField(default="📁", max_length=10)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "KB Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="KBArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comman separated tags", max_length=255
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="eme_kb.kbcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-updated_at"],
            },
        ),
    ]
