# Generated by Django 5.1.2 on 2026-03-06 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eme_chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommember",
            name="sync_id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
