# Generated by Django 5.1.2 on 2026-03-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.IntegerField(db_index=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_favorite", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PastebinSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField()),
                ("syntax", models.CharField(default="plaintext", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "short_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("is_public", models.BooleanField(default=True)),
            ],
        ),
    ]
