# Generated by Django 5.1.2 on 2026-03-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eme_utils", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Memo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                ("content", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_pinned", models.BooleanField(default=False)),
            ],
        ),
    ]
