from django.db import models
from django.conf import settings


class CoreSettings(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='system_settings'
    )
    # Display
    # Display
    node_name = models.CharField(max_length=100, default='EME Node')
    theme = models.CharField(max_length=20, default='dark')
    language = models.CharField(max_length=10, default='uk')
    auto_update = models.BooleanField(default=True)
    
    # Custom Dock Layout (List of app_ids)
    dock_apps = models.JSONField(default=list, blank=True)

    # Notifications
    notification_enabled = models.BooleanField(default=True)
    notification_chat = models.BooleanField(default=True)
    notification_mesh = models.BooleanField(default=True)

    # Mesh / Node
    is_mesh_enabled = models.BooleanField(default=False)
    mesh_sync_interval = models.PositiveIntegerField(default=30, help_text='seconds')

    def __str__(self):
        return f"Settings for {self.user.username}"

class UserAppLayout(models.Model):
    """Stores custom applications built by the user from available modules."""
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='app_layouts')
    name = models.CharField(max_length=100)
    icon = models.CharField(max_length=10, default='📱')
    description = models.TextField(blank=True)
    
    # JSON list of module IDs (e.g., ['profile', 'gallery', 'feed'])
    modules = models.JSONField(default=list)
    order = models.PositiveIntegerField(default=0)
    
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}'s App: {self.name}"

class AIDraftApp(models.Model):
    """Stores generated code drafts from the AI App Builder before they are published."""
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='ai_drafts')
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    component_name = models.CharField(max_length=100, help_text="e.g. EmeGeneratedWall")
    vue_code = models.TextField(help_text="The raw Vue SFC code generated by the LLM")
    
    # AI Agent Config
    agent_prompt = models.TextField(blank=True, help_text="System prompt for the app's AI agent")
    skills = models.JSONField(default=list, blank=True, help_text="List of skills/tools available to the agent")
    
    is_published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Draft: {self.name} by {self.user.username}"
