# Generated by Django 5.1.2 on 2026-03-07 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lobby", "Очікування"),
                            ("night", "Ніч"),
                            ("day", "День"),
                            ("finished", "Завершено"),
                        ],
                        default="lobby",
                        max_length=20,
                    ),
                ),
                ("human_moderator", models.BooleanField(default=False)),
                ("phase_number", models.IntegerField(default=0)),
                ("phase_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_mafia_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("unassigned", "Без ролі"),
                            ("townie", "👨\u200d🌾 Мирний"),
                            ("mafia", "🕴️ Мафія"),
                            ("doctor", "🧑\u200d⚕️ Лікар"),
                            ("detective", "👮 Комісар"),
                        ],
                        default="unassigned",
                        max_length=20,
                    ),
                ),
                ("is_alive", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="eme_mafia.gameroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mafia_players",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("room", "user")},
            },
        ),
        migrations.CreateModel(
            name="GameAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("vote_kill", "Голос за вбивство (Мафія)"),
                            ("vote_lynch", "Повісити (Денне голосування)"),
                            ("heal", "Лікування (Лікар)"),
                            ("inspect", "Перевірка (Комісар)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phase_number", models.IntegerField(default=1)),
                ("is_night_action", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="eme_mafia.gameroom",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions_made",
                        to="eme_mafia.player",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions_received",
                        to="eme_mafia.player",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("text", models.TextField()),
                (
                    "msg_type",
                    models.CharField(
                        choices=[
                            ("public", "Загальний"),
                            ("mafia", "Чат Мафії"),
                            ("system", "Системне"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="eme_mafia.gameroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="eme_mafia.player",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
