# Generated by Django 5.1.2 on 2026-03-04 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("projects", "Projects"),
                            ("network", "Network"),
                            ("generic", "Generic"),
                        ],
                        default="generic",
                        max_length=50,
                    ),
                ),
                ("provider", models.CharField(default="ollama", max_length=50)),
                ("model", models.CharField(default="llama3", max_length=100)),
                ("prompt_preview", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Success"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("error_msg", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
