# Generated by Django 5.1.2 on 2026-02-26 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eme_nav', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='badge_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='eme_nav.navitem'),
        ),
        migrations.AddField(
            model_name='navitem',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='navitem',
            name='visible_to_all',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserNavAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='eme_nav.navitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'nav_item')},
            },
        ),
    ]
