# Generated by Django 5.1.2 on 2026-02-26 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eme_media', '0002_mediafile_file_alter_mediafile_file_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='is_shared',
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='eme_media.collection'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='visibility',
            field=models.CharField(choices=[('private', 'Приватний'), ('friends', 'Для друзів'), ('public', 'Для всіх')], default='private', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'name', 'parent')},
        ),
        migrations.AddField(
            model_name='mediafile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='media_files', to='eme_media.tag'),
        ),
    ]
