# Generated by Django 5.1.2 on 2026-03-06 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eme_media", "0003_tag_alter_collection_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="sync_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="sync_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
