# Generated by Django 5.1.2 on 2026-02-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='is_mesh_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='language',
            field=models.CharField(default='uk', max_length=10),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='mesh_sync_interval',
            field=models.PositiveIntegerField(default=30, help_text='seconds'),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='notification_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresettings',
            name='notification_mesh',
            field=models.BooleanField(default=True),
        ),
    ]
