# Generated by Django 5.1.2 on 2026-03-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "system_settings",
            "0002_coresettings_is_mesh_enabled_coresettings_language_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="dock_apps",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
