# Generated by Django 5.1.2 on 2026-03-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_settings", "0005_aidraftapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapplayout",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userapplayout",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
