# Generated by Django 5.1.2 on 2026-03-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_settings", "0006_userapplayout_description_userapplayout_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidraftapp",
            name="agent_prompt",
            field=models.TextField(
                blank=True, help_text="System prompt for the app's AI agent"
            ),
        ),
        migrations.AddField(
            model_name="aidraftapp",
            name="skills",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of skills/tools available to the agent",
            ),
        ),
    ]
